!function(o,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?define([],e):"object"==typeof exports?exports.hawk=e():o.hawk=e()}(this,function(){return function(o){function e(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return o[t].call(r.exports,r,r.exports,e),r.l=!0,r.exports}var n={};return e.m=o,e.c=n,e.i=function(o){return o},e.d=function(o,n,t){e.o(o,n)||Object.defineProperty(o,n,{configurable:!1,enumerable:!0,get:t})},e.n=function(o){var n=o&&o.__esModule?function(){return o.default}:function(){return o};return e.d(n,"a",n),n},e.o=function(o,e){return Object.prototype.hasOwnProperty.call(o,e)},e.p="",e(e.s=3)}([function(o,e,n){"use strict";o.exports.log=function(o,e,n){e=e||"info",o="[CodeX Hawk]: "+o,"console"in window&&window.console[e]&&(void 0!==n?window.console[e](o,n):window.console[e](o))}},function(o,e,n){"use strict";/*!
 * Codex Hawk client side module
 * https://github.com/codex-team/hawk.client
 *
 * Codex Hawk - https://hawk.so
 * Codex Team - https://ifmo.su
 *
 * @license MIT (c) CodeX 2017
 */
o.exports=function(){var o=n(2),e=n(4),t=n(0),r=null,i=void 0,c=void 0,s=function(n){var s=n.token,l=n.host,f=n.port,p=n.path,w=n.secure,d=n.revision;if(o.socket.host=l||o.socket.host,o.socket.port=f||o.socket.port,o.socket.path=p||o.socket.path,o.socket.secure=void 0!==w?w:o.socket.secure,!s)return void t.log("Please, pass your verification token for Hawk error tracker. You can get it on hawk.so","warn");i=s,d&&(c=d);var h=o.socket;h.onmessage=a.message,h.onclose=a.close,r=e(h),window.addEventListener("error",u)},a={message:function(o){var e=void 0,n=void 0;try{o=JSON.parse(o.data),n=o.type,e=o.message}catch(t){e=o.data,n="info"}t.log("Hawk says: "+e,n)},close:function(){t.log("Connection lost. Errors won't be save. Please, refresh the page","warn")}},u=function(o){var e={token:i,message:o.message,error_location:{file:o.filename,line:o.lineno,col:o.colno,revision:c||null},location:{url:window.location.href,origin:window.location.origin,host:window.location.hostname,path:window.location.pathname,port:window.location.port},stack:o.error.stack||o.error.stacktrace,time:Date.now(),navigator:{ua:window.navigator.userAgent,frame:{width:window.innerWidth,height:window.innerHeight}}};r.send(e)};return{init:s,test:function(){u({message:"Hawk client catcher test",filename:"hawk.js",lineno:0,colno:0,error:{stack:"hawk.js"}})}}}()},function(o,e,n){"use strict";o.exports={socket:{host:"hawk.so",path:"catcher/client",port:8070,secure:!0}}},function(o,e,n){"use strict";o.exports=n(1)},function(o,e,n){"use strict";o.exports=function(o){var e=null,t=n(0),r={CONNECTING:0,OPEN:1,CLOSING:2,CLOSED:3},i=function(){return new Promise(function(n,t){var r="ws"+(o.secure?"s":"")+"://",i=o.host||"localhost",c=o.path?"/"+o.path:"",s=o.port?":"+o.port:"",a=r+i+s+c;e=new WebSocket(a),"function"==typeof o.onmessage&&(e.onmessage=o.onmessage),e.onclose=function(e){"function"==typeof o.onclose&&o.onclose.call(this,e),t()},e.onopen=function(e){"function"==typeof o.onopen&&o.onopen.call(this,e),n()}})},c=function o(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:1;return new Promise(function(n,r){i().then(function(){t.log("Successfully reconnect to socket server","info"),n()},function(){e>0?o(e-1).then(n,r):(t.log("Can't reconnect to socket server","warn"),r())}).catch(function(o){t.log("Error while reconnecting to socket server","error",o)})})},s=function(o){null!==e&&(o=JSON.stringify(o),e.readyState!==r.OPEN?c().then(function(){e.send(o)},function(){t.log("Can't send your data","warn")}):e.send(o))};return i().catch(function(o){t.log("Error while opening socket connection","error",o)}),{send:s}}}])});
//# sourceMappingURL=hawk.js.map