export type { HawkStorage } from './utils/hawk-storage';
export type { RandomGenerator } from './utils/random';
export { HawkUserManager } from './features/hawk-user-manager';
export type { Logger, LogType } from './utils/logger';
export { isLoggerSet, setLogger, resetLogger, log } from './utils/logger';
export { validateUser, validateContext, isValidEventPayload, isValidBreadcrumb } from './utils/validation';
export { isPlainObject, isArray, isClassPrototype, isClassInstance, isString } from './utils/type-guards';
export { Sanitizer } from './utils/sanitizer';
export type { Transport } from './utils/transport';
export type { SanitizerTypeHandler } from './utils/sanitizer';
export { StackParser } from './features/stack-parser';
export { buildElementSelector } from './utils/selector';
export { isErrorProcessed, markErrorAsProcessed } from './utils/event';
export type { BreadcrumbStore, BreadcrumbsAPI, BreadcrumbHint, BreadcrumbInput } from './types/breadcrumb-store';
export type { MessageProcessor, ProcessingPayload } from './types/message-processor';
