export type { HawkStorage } from './storages/hawk-storage';
export type { RandomGenerator } from './utils/random';
export { HawkUserManager } from './users/hawk-user-manager';
export type { Logger, LogType } from './logger/logger';
export { isLoggerSet, setLogger, resetLogger, log } from './logger/logger';
export { validateUser, validateContext, isValidEventPayload, isValidBreadcrumb } from './utils/validation';
export { isPlainObject, isArray, isClassPrototype, isClassInstance, isString } from './utils/type-guards';
export { Sanitizer } from './modules/sanitizer';
export type { Transport } from './transports/transport';
export type { SanitizerTypeHandler } from './modules/sanitizer';
export { StackParser } from './modules/stack-parser';
export { buildElementSelector } from './utils/selector';
export { isErrorProcessed, markErrorAsProcessed } from './utils/event';
export type { BreadcrumbStore, BreadcrumbsAPI, BreadcrumbHint, BreadcrumbInput } from './breadcrumbs/breadcrumb-store';
export type { MessageProcessor, ProcessingPayload } from './messages/message-processor';
export { BaseCatcher } from './catcher';
export type { BeforeSendHook } from './catcher';
